version: '3.9'

services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis

  nginx:
    image: nginx:latest
    ports:
      - 8080:8080
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - bot
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  bot:
    build: ./bot
    depends_on:
      - web

volumes:
  mongo-data:
  redis-data:
